version: '3.4'
services:
  remote-api:
    image: 'kekru/docker-remote-api-tls:v0.4.0'
    ports:
      - '2376:443'
    environment:
      - CREATE_CERTS_WITH_PW=aaa
      - CERT_EXPIRATION_DAYS=20
      - CA_EXPIRATION_DAYS=20
      - CERT_HOSTNAME=aaa
    volumes:
      - /data/certs
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
